BotConfig:
  Activity:
    Type: PLAYING
    Text: ''
    StreamURL: http://wwww.redicraft.eu
    Onlinestatus: ONLINE
  Bottoken: the bottoken goes here
BotInfo:
  version: 19700101_v0.0.0abs
  online:
    ts: 1597421015750
    string: 14/08/2020 - 18:03:35
MySQL:
  Host: localhost
  Port: 3306
  Database: database
  Username: username
  Password: password
