BotConfig:
  Activity:
    Type: PLAYING
    Text: ''
    StreamURL: http://wwww.redicraft.eu
    Onlinestatus: ONLINE
  Bottoken: the bottoken goes here
BotInfo:
  version: 19700101_v0.0.0abs
  online:
    ts: 1593048545203
    string: 25/06/2020 - 03:29:05
MySQL:
  Host: localhost
  Port: 3306
  Database: database
  Username: username
  Password: password
