BotConfig:
  Activity:
    Type: PLAYING
    Text: Being a baby.
    StreamURL: https://www.youtube.com/channel/UCBJhuPBSaucwk_TthujYrBw
    Onlinestatus: ONLINE
  Bottoken: the bottoken goes here
  Bootlogo: 0
  DEncryptPass: password
BotInfo:
  version: 19700101_v0.0.0abs
  online:
    ts: 1662232226714
    string: 03/09/2022 - 21:10:26 pm CEST
MySQL:
  Host: localhost
  Port: 3306
  Database: database
  Username: username
  Password: password
