BotConfig:
  Activity:
    Type: PLAYING
    Text: Being a baby.
    StreamURL: https://www.youtube.com/channel/UCBJhuPBSaucwk_TthujYrBw
    Onlinestatus: ONLINE
  Bottoken: the bottoken goes here
  Bootlogo: 0
  DEncryptPass: password
BotInfo:
  version: 19700101_v0.0.0abs
  online:
    ts: 1680960927951
    string: 08/04/2023 - 15:35:27 PM MESZ
MySQL:
  Host: localhost
  Port: 3306
  Database: database
  Username: username
  Password: password
